config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :students
  resources :masters
  resources :courses
  resources :cohorts
  resources :admins

  get 'welcome/index'
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    belongs_to :master
    has_many :students
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]
  before_action :set_students, only: [:show]
  
  def index
    @cohorts = Cohort.all
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    @cohort.save!
    redirect_to @cohort
  end

  def update
    @cohort.update(cohort_params)
    redirect_to @cohort
  end

  def edit
    @cohort
  end

  def destroy
    @cohort.destroy
    redirect_to @cohort
  end

  def show
    @cohort
  end

  private
  def set_cohort
    @cohort = Cohort.find(params[:id])
  end

  def set_students
    @students = Student.where(cohort_id: params[:id]).all
    @students_unassigned = Student.where(cohort_id: nil).all
  end

  def cohort_params
    params.require(:cohort).permit(
      :name,
      :start_date,
      :end_date,
      :course_id,
      :master_id,
    )
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end

end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<%= bootstrap_form_for @cohort do |form| %>
  <%= form.text_field :name %>
  <%= form.date_field :start_date %>
  <%= form.date_field :end_date %>
  <%= form.select(:course_id, options_from_collection_for_select(Course.all, :id, :name)) %>
  <%= form.select(:master_id, options_from_collection_for_select(Master.all, :id, :full_name)) %>
  <%= form.submit %>
<% end %>

app/views/cohorts/create.html.erb
<h1>Cohorts#create</h1>
<p>Find me in app/views/cohorts/create.html.erb</p>

app/views/cohorts/destroy.html.erb
<h1>Cohorts#destroy</h1>
<p>Find me in app/views/cohorts/destroy.html.erb</p>

app/views/cohorts/edit.html.erb
<h1>Cohort edit</h1>

<%= render 'cohorts/form' %>

app/views/cohorts/index.html.erb
<h1>Cohorts of our school:</h1>
 
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th scope="col">Course</th>
      <th scope="col">Master</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @cohorts.each do |cohort| %>
    <tr>
      <td><%= cohort.name %></td>
      <td><%= cohort.start_date %></td>
      <td><%= cohort.end_date %></td>
      <td><%= cohort.course.name %></td>
      <td><%= cohort.master.full_name %></td>
      <td>
        <%= link_to 'Show', cohort_path(cohort) %>
        <% if is_admin_user %>
          <%= link_to 'Edit', edit_cohort_path(cohort) %>
          <%= link_to 'Delete', cohort_path(cohort), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>


<p>
<% if is_admin_user %>
  <%= link_to 'Add cohort', new_cohort_path(@cohort) %>
<% end %>
</p>

app/views/cohorts/new.html.erb
<h1>New Cohort</h1>

<%= render 'cohorts/form' %>

app/views/cohorts/show.html.erb
<p>
  <strong>Name of cohort:</strong>
  <%= @cohort.name %>
</p>
 
<p>
  <strong>Start date:</strong>
  <%= @cohort.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @cohort.end_date %>
</p>

<p>
  <strong>Master:</strong>
  <%= link_to @cohort.master.full_name, master_path(@cohort.master) %>
</p>

<p>
<% if is_admin_user %>
  <%= link_to 'Edit', edit_cohort_path(@cohort) %>
  <%= link_to 'Delete', cohort_path(@cohort), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</p>

<h3>Cohort Students:</h3>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Nickname</th>
      <th scope="col">Age</th>
      <th scope="col">Education</th>
      <th scope="col">Cohort</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><img class="profile-pic" src="<%= student.picture %>"/></td>
      <td><%= student.nickname %></td>
      <td><%= student.age %></td>
      <td><%= student.education %></td>
      <td><%= student[:cohort_id] ? Cohort.find(student[:cohort_id]).try(:name) : '' %></td>
      <td><%= link_to 'Show', student_path(student) %>
      <% if is_admin_user %>
        <%= link_to 'Edit', edit_student_path(student) %>
        <%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if is_admin_user %>
<h3>Unassigned students:</h3>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Nickname</th>
      <th scope="col">Age</th>
      <th scope="col">Education</th>
      <th scope="col">Cohort</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @students_unassigned.each do |student_unassigned| %>
    <tr>
      <td><img class="profile-pic" src="<%= student_unassigned.picture %>"/></td>
      <td><%= student_unassigned.nickname %></td>
      <td><%= student_unassigned.age %></td>
      <td><%= student_unassigned.education %></td>
      <td><%= student_unassigned[:cohort_id] ? Cohort.find(student_unassigned[:cohort_id]).try(:name) : '' %></td>
      <td><%= link_to 'Show', student_path(student_unassigned) %>
      <% if is_admin_user %>
        <%= link_to 'Edit', edit_student_path(student_unassigned) %>
        <%= link_to 'Delete', student_path(student_unassigned), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/cohorts/update.html.erb
<h1>Cohort edit</h1>

<%= render 'cohorts/form' %>