config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :students
  resources :masters
  resources :courses
  resources :cohorts
  resources :admins

  get 'welcome/index'
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_one :user, as: :userable, dependent: :destroy
    accepts_nested_attributes_for :user, allow_destroy: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    belongs_to :master
    has_many :students
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts
end

app/models/master.rb
class Master < ApplicationRecord
    has_many :cohorts
    has_one :user, as: :userable, dependent: :destroy
    accepts_nested_attributes_for :user, allow_destroy: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/student.rb
class Student < ApplicationRecord
    has_one :cohort
    has_one :user, as: :userable, dependent: :destroy
    accepts_nested_attributes_for :user, allow_destroy: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userable, polymorphic: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
  
  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
    @admin.build_user
  end

  def create
    @admin = Admin.new(admin_params)
    @admin.save!
    redirect_to @admin
  end

  def update
    @admin.update(admin_params)
  end

  def edit
    @admin
  end

  def destroy
    @admin.destroy
  end

  def show
    @admin
  end

  private
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(
      :first_name,
      :last_name,
      :user_attributes => [
        :email,
        :password
      ]
    )
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]
  before_action :set_students, only: [:show]
  
  def index
    @cohorts = Cohort.all
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    @cohort.save!
    redirect_to @cohort
  end

  def update
    @cohort.update(cohort_params)
    redirect_to @cohort
  end

  def edit
    @cohort
  end

  def destroy
    @cohort.destroy
    redirect_to @cohort
  end

  def show
    @cohort
  end

  private
  def set_cohort
    @cohort = Cohort.find(params[:id])
  end

  def set_students
    @students = Student.where(cohort_id: params[:id]).all
    @students_unassigned = Student.where(cohort_id: nil).all
  end

  def cohort_params
    params.require(:cohort).permit(
      :name,
      :start_date,
      :end_date,
      :course_id,
      :master_id,
    )
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.save!
    redirect_to @course
  end

  def update
    @course.update(course_params)
    redirect_to @course
  end

  def edit
    @course
  end

  def destroy
    @course.destroy
    redirect_to @course
  end

  def show
    @course
    @cohorts = Cohort.where(course_id: @course.id)
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :hours)
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end

end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_master, only: [:show, :edit, :update, :destroy]

  def index
    @masters = Master.all
  end

  def new
    @master = Master.new
    @master.build_user
  end

  def create
    @master = Master.new(master_params)
    @master.save!
    redirect_to @master
  end

  def update
    @master.update(master_params)
    redirect_to @master
  end

  def edit
    @master
  end

  def destroy
    @master.destroy
    redirect_to @master
  end

  def show
    @master
  end

  private
  def set_master
    @master = Master.find(params[:id])
  end

  def master_params
    params.require(:master).permit(
      :picture,
      :abilities,
      :first_name,
      :last_name,
      :age,
      :salary,
      :education,
      :user_attributes => [
        :email,
        :password
      ]
    )
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin_user
    if current_user.userable_type != "Admin"
      return false
    end
    return true
  end

  def is_master_user
    if current_user.userable_type != "Master"
      return false
    end
    return true
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
     # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end

      # Returns the current logged-in user (if any).
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/_form.html.erb
<%= bootstrap_form_for @admin do |form| %>
  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  <%= form.fields_for :user do |u| %>
    <%= u.email_field :email, placeholder: "Enter Email", label: "Email address", help: "We'll never share your email with anyone else" %>
    <%= u.password_field :password, placeholder: "Password" %>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/destroy.html.erb
<h1>Admins#destroy</h1>
<p>Find me in app/views/admins/destroy.html.erb</p>

app/views/admins/edit.html.erb
<h1>Admin edit</h1>

<%= render 'admins/form' %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>
 
<ul>
  <% @admins.each do |admin| %>
      <li><%= admin.first_name %></li>
      <li><%= admin.last_name %></li>
      <li><%= link_to 'Show', admin_path(admin) %></li>
      <% if is_admin_user %>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Delete', admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  <% end %>
</ul>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'admins/form' %>

app/views/admins/show.html.erb
<p>
  <strong>First name</strong>
  <%= @admin.first_name %>
</p>

<p>
  <strong>Last name</strong>
  <%= @admin.last_name %>
</p>

app/views/admins/update.html.erb
<h1>Admin edit</h1>

<%= render 'admins/form' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><img src="/assets/logo.png"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cohorts">Cohorts<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/courses">Courses<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/masters">Masters<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/students">Students<span class="sr-only"></span></a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvelLyceum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Marvel" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer class="footer footer-dark bg-dark sticky-bottom">
      <div class="container">
        <div class="social-info">
            <a href="https://www.instagram.com/108masha/" target="_blank"><i class="fab fa-facebook-square"></i></a>
            <a href="https://www.instagram.com/108masha/" target="_blank"><i class="fab fa-instagram"></i></a>
            <a href="https://www.instagram.com/108masha/" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/108masha/" target="_blank"><i class="fas fa-map-marker-alt"></i></a>
        </div>
      </div>
    </footer>
  </body>
</html>