config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :students
  resources :masters
  resources :courses
  resources :cohorts
  resources :admins

  get 'welcome/index'
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    has_one :cohort
    has_one :user, as: :userable, dependent: :destroy
    accepts_nested_attributes_for :user, allow_destroy: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]  
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
    @student.build_user
  end

  def create
    @student = Student.new(student_params)
    @student.save!
    redirect_to @student
  end

  def update
    @student.update(student_params)
    redirect_to @student
  end

  def edit
    @student
  end

  def destroy
    @student.destroy
    redirect_to @student
  end

  def show
    @student = Student.find(params[:id])
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(
      :picture,
      :nickname,
      :abilities,
      :first_name,
      :last_name,
      :age,
      :education,
      :cohort_id,
      :user_attributes => [
        :email,
        :password
      ]
    )
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= bootstrap_form_for @student do |form| %>
  <%= form.text_field :picture %>
  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  <%= form.text_field :nickname %>
  <%= form.text_field :abilities %>  
  <%= form.number_field :age %>
  <%= form.select :education, ['HS', 'College', 'Masters', 'PhD'] %>
  <%= form.select(:cohort_id, options_from_collection_for_select(Cohort.all, :id, :name, @student.cohort_id), { include_blank: true }) %>
  <%= form.fields_for :user do |u| %>
    <%= u.email_field :email, placeholder: "Enter Email", label: "Email address", help: "We'll never share your email with anyone else" %>
    <%= u.password_field :password, placeholder: "Password" %>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Student edit</h1>

<%= render 'students/form' %>

app/views/students/index.html.erb
<h1>Our Students:</h1>
 
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Nickname</th>
      <th scope="col">Age</th>
      <th scope="col">Education</th>
      <th scope="col">Cohort</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><img class="profile-pic" src="<%= student.picture %>"/></td>
      <td><%= student.nickname %></td>
      <td><%= student.age %></td>
      <td><%= student.education %></td>
      <td><%= student[:cohort_id] ? Cohort.find(student[:cohort_id]).try(:name) : '' %></td>
      <td><%= link_to 'Show', student_path(student) %>
      <% if is_admin_user %>
        <%= link_to 'Edit', edit_student_path(student) %>
        <%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
<% if is_admin_user %>
  <%= link_to 'Add student', new_student_path(@student) %>
<% end %>
</p>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'students/form' %>

app/views/students/show.html.erb
<p>
  <img src="<%= @student.picture %>"/>
</p>

<p>
  <strong>Real name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @student.nickname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Education:</strong>
  <%= @student.education %>
</p>

<p>
  <strong>Current cohort:</strong>
  <%= @student[:cohort_id] ? Cohort.find(@student[:cohort_id]).try(:name) : '' %>
</p>

<p>
  <strong>Abilities:</strong>
  <%= @student.abilities %>
</p>

<p>
<% if is_admin_user %>
  <%= link_to 'Edit', edit_student_path(@student) %>
  <%= link_to 'Delete', student_path(@student), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</p>

app/views/students/update.html.erb
<h1>Student edit</h1>

<%= render 'students/form' %>