config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :students
  resources :masters
  resources :courses
  resources :cohorts
  resources :admins

  get 'welcome/index'
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master.rb
class Master < ApplicationRecord
    has_many :cohorts
    has_one :user, as: :userable, dependent: :destroy
    accepts_nested_attributes_for :user, allow_destroy: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :is_admin_user, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_master, only: [:show, :edit, :update, :destroy]

  def index
    @masters = Master.all
  end

  def new
    @master = Master.new
    @master.build_user
  end

  def create
    @master = Master.new(master_params)
    @master.save!
    redirect_to @master
  end

  def update
    @master.update(master_params)
    redirect_to @master
  end

  def edit
    @master
  end

  def destroy
    @master.destroy
    redirect_to @master
  end

  def show
    @master
  end

  private
  def set_master
    @master = Master.find(params[:id])
  end

  def master_params
    params.require(:master).permit(
      :picture,
      :abilities,
      :first_name,
      :last_name,
      :age,
      :salary,
      :education,
      :user_attributes => [
        :email,
        :password
      ]
    )
  end

  def is_admin_user
    if current_user.userable_type != "Admin"
      flash[:notice] = 'Only admins can do it!'
      redirect_to(:action => 'index')
      return false
    end
  end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/_form.html.erb
<%= bootstrap_form_for @master do |form| %>
  <%= form.text_field :picture %>
  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  <%= form.number_field :age %>
  <%= form.text_field :abilities %>
  <%= form.number_field :salary %>
  <%= form.select :education, ['HS', 'College', 'Masters', 'PhD'] %>
  <%= form.fields_for :user do |u| %>
    <%= u.email_field :email, placeholder: "Enter Email", label: "Email address", help: "We'll never share your email with anyone else" %>
    <%= u.password_field :password, placeholder: "Password" %>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/masters/create.html.erb
<h1>Masters#create</h1>
<p>Find me in app/views/masters/create.html.erb</p>

app/views/masters/destroy.html.erb
<h1>Masters#destroy</h1>
<p>Find me in app/views/masters/destroy.html.erb</p>

app/views/masters/edit.html.erb
<h1>Master edit</h1>

<%= render 'masters/form' %>

app/views/masters/index.html.erb
<h1>Our masters:</h1>

<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Education</th>
      <% if is_admin_user %>
        <th scope="col">Salary</th>
      <% end %>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @masters.each do |master| %>
    <tr>
      <td><img class="profile-pic" src="<%= master.picture %>"/></td>
      <td><%= master.full_name %></td>
      <td><%= master.age %></td>
      <td><%= master.education %></td>
      <% if is_admin_user %>
        <td><%= master.salary %></td>
      <% end %>
      <td>
      <%= link_to 'Show', master_path(master) %>
      <% if is_admin_user %>
        <%= link_to 'Edit', edit_master_path(master) %>
        <%= link_to 'Delete', master_path(master), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
<% if is_admin_user %>
  <%= link_to 'Add master', new_master_path(@master) %>
<% end %>
</p>

app/views/masters/new.html.erb
<h1>New Master</h1>

<%= render 'masters/form' %>

app/views/masters/show.html.erb
<p>
  <img src="<%= @master.picture %>"/>
</p>

<p>
  <strong>First name:</strong>
  <%= @master.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @master.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @master.age %>
</p>

<% if is_admin_user %>
<p>
  <strong>Salary $:</strong>
  <%= @master.salary %>
</p>
<% end %>


<p>
  <strong>Education:</strong>
  <%= @master.education %>
</p>

<p>
  <strong>Cohorts:</strong>
  <ul>
  <% @master.cohorts.each do |cohort| %>
   <li><%= link_to cohort.name, cohort_path(cohort.id) %></li>
  <% end %>
  </ul>
</p>

<p>
  <strong>Abilities:</strong>
  <%= @master.abilities %>
</p>

<p>
<% if is_admin_user %>
  <%= link_to 'Edit', edit_master_path(@master) %>
  <%= link_to 'Delete', master_path(@master), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</p>

app/views/masters/update.html.erb
<h1>Master edit</h1>

<%= render 'masters/form' %>